on:
  push:
    tags:
      - "*"

name: Create a Release

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Create release
        run: >-
          latest_tag="$(git describe --tags --abbrev=0)";
          gh release create "${latest_tag}" --generate-notes;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 5
